#ifndef __POUS_H
#define __POUS_H

#include "accessor.h"
#include "iec_std_lib.h"

// PROGRAM PROGRAM0
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_LOCATED(BOOL,OUT0)
  __DECLARE_LOCATED(BOOL,OUT1)
  __DECLARE_LOCATED(BOOL,OUT2)
  __DECLARE_LOCATED(BOOL,OUT3)
  __DECLARE_LOCATED(BOOL,OUT4)
  __DECLARE_LOCATED(BOOL,OUT5)
  __DECLARE_LOCATED(BOOL,OUT6)
  __DECLARE_LOCATED(BOOL,OUT7)
  __DECLARE_VAR(TIME,TIMEON0)
  __DECLARE_VAR(TIME,TIMEON1)
  __DECLARE_VAR(TIME,TIMEON2)
  __DECLARE_VAR(TIME,TIMEON3)
  __DECLARE_VAR(TIME,TIMEON4)
  __DECLARE_VAR(TIME,TIMEON5)
  __DECLARE_VAR(TIME,TIMEON6)
  __DECLARE_VAR(TIME,TIMEON7)
  __DECLARE_VAR(TIME,TIMEOFF0)
  __DECLARE_VAR(TIME,TIMEOFF1)
  __DECLARE_VAR(TIME,TIMEOFF2)
  __DECLARE_VAR(TIME,TIMEOFF3)
  __DECLARE_VAR(TIME,TIMEOFF4)
  __DECLARE_VAR(TIME,TIMEOFF5)
  __DECLARE_VAR(TIME,TIMEOFF6)
  __DECLARE_VAR(TIME,TIMEOFF7)
  TON TON0;
  TOF TOF0;
  TON TON1;
  TOF TOF1;
  TON TON2;
  TOF TOF2;
  TON TON3;
  TOF TOF3;
  TON TON4;
  TOF TOF4;
  TON TON5;
  TOF TOF5;
  TON TON6;
  TOF TOF6;
  TON TON7;
  TOF TOF7;

} PROGRAM0;

void PROGRAM0_init__(PROGRAM0 *data__, BOOL retain);
// Code part
void PROGRAM0_body__(PROGRAM0 *data__);
#endif //__POUS_H
